core/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  mount Rswag::Ui::Engine => "/api-docs"
  mount Api::Base, at: "/api"

  # Defines the root path route ("/")
  root "users#welcome"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :users, except: %i[destroy] do
    get :me, on: :collection
    get "me/missing_organization", on: :collection, to: "users#missing_organization"
    get :logout, on: :collection, to: "session#logout_user"
    post :logout, on: :collection, to: "session#logout_user"
    get :invitations, on: :collection
    get :accept_invitation, on: :collection
    get :reject_invitation, on: :collection
    get "invitation/:invite_code", on: :collection, to: "users#invitation", as: "invitation"
    post "register/:invite_code", on: :collection, to: "users#register", as: "register"
    post :toggle_archive, on: :member
    get :accept_terms, on: :collection
    post :accept_terms, on: :collection
    get :switch_organization, on: :collection
    get :resend_invitation, on: :member
  end

  resources :organization_users do
    resources :privileges, only: [:index] do
      put :update, on: :collection
    end
  end

  resources :password_resets, only: %i[new create edit update]

  post "login_local" => "session#create", as: :login_local

  # oauth
  post "session/callback"
  get  "session/callback"
  get  "session/:provider" => "session#oauth", as: :auth_at_provider
  get  "oauth/callback/microsoft" => "session#callback", defaults: { provider: "microsoft" }

  resources :sources, only: %i[show destroy] do
    get :show_secret
    get :dynamic_form_template
    get :dynamic_form, on: :collection
    post :dynamic_form_submit, on: :collection
    get :view_data
    post :manual_upload
    post :trigger_now
    get :edit_project
    post :update_project
    get "public_recorded/:code", on: :collection,
                                 to: "sources#public_recorded", as: :public_recorded
    post "public_recorded_upload/:code", on: :collection,
                                         to: "sources#public_recorded_upload", as: :public_recorded_upload
    post :reprocess
    post :delete_data_and_imports
    get :csv_update
    post :csv_update_submit
    get :backfill
    get :backfill_completely
    post :backfill_from_date

    resources :imports, only: :index
  end

  resources :projects do
    resources :visibilities, except: :index, shallow: true
    get :view_data
    get :view_data_rbf

    # /sources/dynamic_form
    get :dynamic_form, on: :collection
    post :dynamic_form_submit, on: :collection
  end

  resources :build_source, only: %i[show update], controller: "sources/build"

  resources :imports, only: %i[show destroy] do
    get :download
    post :reprocess
  end

  resources :encrypted_blob

  get "demo" => "demo#index"
  get "demo/show" => "demo#show"
  get "demo/wrap_key" => "demo#wrap_key"
  post "demo/post_key" => "demo#post_key"
  post "demo/ajax_test" => "demo#ajax_test"
  get "demo/easy_web_crypto" => "demo#easy_web_crypto"

  resources :analytics, only: %i[index show] do
    get "grafana_new/:type", on: :collection, to: "analytics#grafana_new", as: :grafana_new
    get "preview/:board_uid", on: :collection, to: "analytics#preview", as: :preview
  end

  resources :docs, only: %i[index show]

  get "exports" => "exports#index"
  get "exports/export"
  get "exports/export_form"

  match "ping", to: "status#ping", via: %i[get post]

  get "organizations/mine"
  resources :organizations, except: %i[new create] do
    get :show_token
  end

  get "shared_keys_vault/edit" => "shared_keys_vault#edit"
  post "shared_keys_vault/create" => "shared_keys_vault#create"
  post "shared_keys_vault/delete" => "shared_keys_vault#delete"

  resources :rbf_claims do
    get :summary, on: :member
    get :show_do_data_collection, on: :member
    get :print_submitted, on: :member
    get :show_do_assign_verifiers, on: :member
    get :show_do_verification, on: :member
    get :download_verification_csv, on: :member
    get :show_do_payment, on: :member
    get :show_paid_out, on: :member
    get :show_verification_result, on: :member
    get :show_print_voucher, on: :member
    get :print_voucher, on: :member

    post :do_data_collection, on: :member
    post :do_data_collection_add_all, on: :member
    post :do_assign_verifiers, on: :member
    post :do_verification, on: :member
    post :do_device_verification, on: :member
    post :do_payment, on: :member
    post :do_sample_secondary_verification, on: :member

    get :device_details, on: :member
    get :device_claim, on: :member
    post "event/:event", on: :member, to: "rbf_claims#event", as: :event
    get "download/:type", on: :member, to: "rbf_claims#download", as: :download
  end

  resources :rbf_dashboard, only: :index do
    get :rbf_products, on: :collection
    post :setup_project, on: :collection
    post :add_agent, on: :collection
    post :toggle_agent, on: :collection
  end
end

core/app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  helper UserHelper
  skip_before_action :require_login, only: %i[welcome invitation register]
  skip_before_action :check_accepted_terms, only: %i[accept_terms]
  skip_before_action :capture_missing_organization,
                     only: %i[missing_organization switch_organization accept_invitation reject_invitation]
  after_action :verify_authorized, except: %i[welcome]

  @header_section = "Organization"

  def show
    @user = User.find params[:id]
    authorize @user
    @page_title = @user
  end

  def me
    @header_section = "User"
    @user = current_user
    authorize @user
    @page_title = @user
    render :show
  end

  def welcome
    if Current.user && Current.organization&.rbf_submitting?
      redirect_to rbf_dashboard_index_path
    else
      @header_section = nil
      @page_title = t(".welcome")
      @hide_page_title = true
    end
  end

  def new
    @user = User.new organization: Current.organization
    authorize @user
  end

  def edit
    @user = authorize User.find params[:id]
    @header_section = "User" if @user == Current.user
    @page_title = "Edit #{@user}"
  end

  def missing_organization
    @user = authorize Current.user
    redirect_to root_path if Current.user.organization
  end

  def switch_organization
    authorize Current.user
    Current.user.switch_organization! params[:organization_id]
    redirect_to root_path
  end

  # A new user can be invited to an organization via the invitation form.
  # If the user is already on the Prospect platform, we invite him to join this organization
  # else he will be created like any new user.
  # Once an already existing user is invited, he can accept or reject the invite himself.

  def create
    #
    # WE MIGHT WANT TO REFACTOR THAT INTO ITS OWN SERVICE.-
    # IF WE DO TAKE THE ALMOST IDENTICAL CODE IN Organization#invite_manager! too
    # AND REFACTOR TOGETHER!
    #
    @user = User.by_normalized_email create_user_params[:email]

    organization = Organization.find(create_user_params[:organization_id])
    raise "Only admins can add users to a different organization" if
      organization != Current.organization && !Current.user.admin?

    if @user
      # user exists
      authorize @user
      if @user.user_in_organization?(create_user_params[:organization_id])
        redirect_to organizations_mine_path, notice: t(".already_part_of_organization")
      elsif create_user_params[:organization_id].to_i.in?(@user.invitations.pluck(:organization_id))
        redirect_to organizations_mine_path, notice: t(".already_invited")
      else
        @user.organizations << organization
        ou = @user.invitations.find_by(organization:)

        ou.apply_privilege_template(create_user_params[:priv_template])

        @user.mail_organization_invite(organization)
        redirect_to organizations_mine_path, notice: t(".invited")
      end
    else
      # user doesn't exist yet, create it
      @user = User.new create_user_params
      raise "Only admins can create other admins" if !Current.user.admin? && @user.admin?

      authorize @user
      if @user.save
        ou = @user.current_organization_user

        ou.apply_privilege_template(create_user_params[:priv_template])

        redirect_to organizations_mine_path, notice: t(".invited")
      else
        render :new, status: :unprocessable_content
      end
    end
  end

  def update
    @user = User.find params[:id]
    @user.assign_attributes update_user_params.compact_blank

    @user.admin = params[:user][:admin] if Current.user.admin? && params[:user][:admin].present? # only admins can create/disable other admins

    authorize @user

    if @user.save
      redirect_to @user, notice: t(".updated")
    else
      @page_title = "Edit #{@user}"
      render :edit, status: :unprocessable_content
    end
  end

  def toggle_archive
    @user = authorize User.find params[:id]

    if @user.invited?
      @user.destroy!
      redirect_to organizations_mine_path, notice: t(".destroyed")
    elsif @user.active?
      @user.archive
      @user.save!
      redirect_to organizations_mine_path, notice: t(".archived")
    elsif @user.archived?
      @user.update! archived_at: nil
      redirect_to organizations_mine_path, notice: t(".reactivated")
    else
      raise "Unhandled user state, can not toggle nothing!"
    end
  end

  def resend_invitation
    organization_user = OrganizationUser.where(user_id: params[:id], organization: Current.organization).first

    authorize organization_user.user

    UserMailer.with(user: organization_user.user, inviting_user: Current.user).invite.deliver_later

    redirect_back_or_to :root, notice: "The invitation has been resent."
  end

  def invitations
    authorize Current.user
  end

  def invitation
    @user = User.find_by! invite_code: params[:invite_code]
    authorize @user
  rescue Pundit::NotAuthorizedError
    redirect_to root_path, alert: t(".already_registered")
  end

  def accept_invitation
    authorize Current.user

    invitation = Current.user.invitations.find_by(organization_id: invitation_params[:organization_id])
    if invitation
      invitation.activate!
      flash[:notice] = t(".accepted")
      Current.user.switch_organization! invitation.organization unless Current.user.organization
    end

    redirect_to Current.user.invitations.any? ? invitations_users_path : root_path
  end

  def reject_invitation
    authorize Current.user
    invitation = Current.user.invitations.find_by(organization_id: invitation_params[:organization_id])
    if invitation
      invitation.destroy
      flash[:notice] = t(".rejected")
    end
    redirect_to invitations_users_path
  end

  def register
    @user = User.find_by! invite_code: params[:invite_code]
    authorize @user

    @user.assign_attributes register_user_params
    @user.activate

    if @user.save
      @user.mail_welcome
      redirect_to root_path, notice: t(".complete_please_login")
    else
      render :invitation, status: :unprocessable_content
    end
  end

  def accept_terms
    @user = authorize current_user
    redirect_to root_path and return if @user.all_terms_accepted?
    return unless request.post?

    values = accept_terms_user_params.to_h.map do |k, v|
      case v
      when "1"
        version = Rails.configuration.current_terms_version[k]
        [k, { accepted: true,
              ip: request.ip,
              version:,
              date: Time.zone.now }]
      else
        [k, { accepted: false }]
      end
    end
    @user.assign_attributes values.to_h
    if @user.all_terms_accepted? && @user.save
      flash[:notice] = I18n.t("users.terms_and_conditions.accepted")
      redirect_to root_path
    else
      flash[:alert] = I18n.t("users.terms_and_conditions.accept_all")
      render :accept_terms, status: :unprocessable_content
    end
  end

  private

  def invitation_params
    params.permit :organization_id
  end

  def create_user_params
    params.require(:user).permit :email, :priv_template, :organization_id
  end

  def update_user_params
    params.require(:user).permit :username, :email, :organization_id, :password, :password_confirmation
  end

  def register_user_params
    params.require(:user).permit :emanresu_in_reverse, :password, :password_confirmation
  end

  def accept_terms_user_params
    params.require(:user).permit :terms_of_use, :data_protection_policy, :code_of_conduct
  end
end

core/app/helpers/user_helper.rb
# frozen_string_literal: true

module UserHelper
  def show_invitation_url?(invited_user)
    invited_user.invited? && invited_user.created_at < 5.minutes.ago && policy(invited_user).show_invitation_url?
  end
end

core/app/views/users/accept_terms.html.haml
%div
  -# maybe check if the version changed and modify the message accordingly
  %h2.font-bold.text-xl.mt-12.mb-8
    = I18n.t("users.terms_and_conditions.accept_before")
  = form_for :user, method: :post, action: "users/accept_terms" do |f|
    .field.mt-4
      %div.h-96.overflow-scroll
        = render "terms_of_use"
        = render "data_protection_policy"
        = render "code_of_conduct"
      %div.my-6.flex.items-center 
        = f.check_box :terms_of_use, class: "accent-primary text-primary focus:ring-primary"
        %span.ml-1.font-bold
          = f.label :terms_of_use, I18n.t("users.terms_and_conditions.accept_terms_of_use")
      %div
        %div.my-6.flex.items-center 
          = f.check_box :data_protection_policy, class: "accent-primary text-primary focus:ring-primary"
          %span.ml-1.font-bold
            = f.label :data_protection_policy, I18n.t("users.terms_and_conditions.accept_data_protection_policy")
      %div
        %div.mt-6.flex.items-center
          = f.check_box :code_of_conduct, class: "accent-primary text-primary focus:ring-primary"
          %span.ml-1.font-bold
            = f.label :code_of_conduct, I18n.t("users.terms_and_conditions.accept_code_of_conduct")
      %div.mt-5
        = f.submit :accept, **tw_submit_prominent_args("rounded-full shadow")

core/app/views/users/edit.html.haml
= content_for :breadcrumbs do
  = render "breadcrumb" do
    = link_to @user

= form_for @user, url: user_path, method: :patch do |f|

  .wrapper{class: "w-1/2"}

    - if @user.errors.any?
      %ul.text-sm.mb-6.text-pink
        - @user.errors.to_a.each do |e|
          %li= e

    - if @user.invited?
      .field.mb-4
        = f.text_field :email, placeholder: :email, required: true, **tw_text_input_args("w-full")
    - else
      .field.mb-4
        = f.text_field :username, placeholder: :name, required: true, **tw_text_input_args("w-full")

    - if Current.user.admin?
      .field.mt-4
        = f.check_box :admin, **tw_select_input_args
        %span.ml-1
          = f.label :admin, "Admin", class: "mb-1 font-semibold uppercase text-dark/80"

    - if @user.authentications.empty? && @user.active?
      .field.mt-4
        = f.password_field :password, placeholder: "Password: min #{User::MIN_PW_LENGTH} characters", **tw_text_input_args("w-full")
      .field.mt-4
        = f.password_field :password_confirmation, placeholder: :password_confirmation, **tw_text_input_args("w-full")

    .field.mt-10
      = f.submit "Update", **tw_submit_prominent_args

core/app/views/users/invitation.html.haml
- content_for :page_title do
  = "Register #{@user.email}"

= form_for @user, url: register_users_path, method: :post do |f|

  .wrapper{class: "w-1/2"}

    - if @user.errors.any?
      %ul.text-sm.mb-6.text-pink
        - @user.errors.to_a.each do |e|
          %li= e

    = f.hidden_field :invite_code # use this to prevent just submitting some user id.

    .field.hidden
      = f.email_field :email

    .field
      -# instead of username we take something different - password managers will pick then rather the hidden email input :)
      = f.text_field :emanresu_in_reverse, placeholder: :name, required: true, **tw_text_input_args("w-full")
    .field.mt-4
      = render "secret_visibility_wrapper" do
        = f.password_field :password, data: {"password-visibility-target": :input}, placeholder: "Password: min 12 characters", required: true, **tw_password_input_args("w-full flex"), autocomplete: "new-password", spellcheck: false
    .field.mt-4
      = render "secret_visibility_wrapper" do
        = f.password_field :password_confirmation, data: {"password-visibility-target": :input}, placeholder: :password_confirmation, required: true, **tw_password_input_args("w-full flex"), autocomplete: "new-password", spellcheck: false
    .field.mt-10
      = f.submit "Register", **tw_submit_prominent_args

  - if Rails.application.config.google_auth
    .wrapper{class: "w-1/2"}
      .mt-10.text-sm= "If your email #{@user.email} is hosted by google, you can also register via google"
      .field.mt-8
        = link_to auth_at_provider_path(provider: :google), class: "mt-5" do
          %button.rounded{tw_submit_prominent_args}
            = t('users.register.register_with_google')
  - if Rails.application.config.ms_auth
    .wrapper{class: "w-1/2"}
      .mt-10.text-sm= "If your email #{@user.email} is hosted by microsoft, you can also register via microsoft"
      .field.mt-8
        = link_to auth_at_provider_path(provider: :microsoft), class: "mt-5" do
          %button.rounded{tw_submit_prominent_args}
            = t('users.register.register_with_microsoft')

core/app/views/users/invitations.html.haml
- content_for :page_title do
  Invitations

#invitations
- if Current.user.invitations.any?
  .w-full.grid.grid-cols-6.gap-3.py-3.px-2.text-l
    .user-name{class: "col-span-3 font-semibold"}
      Organization
- else
  %div{class: "px-2"}
    No open invitations

- Current.user.invitations.each do |u|
  .w-full.grid.grid-cols-6.gap-3.py-3.px-2.text-lg
    .organization-name{class: "col-span-3"}
      = u.organization.name
    %span.flex.ml-4.cursor-pointer.hover:text-primary.text-sm
      = link_to "Accept", accept_invitation_users_path(organization_id: u.organization_id), **tw_link_prominent_args("rounded-l-lg", without: %w[rounded-full])
      = link_to "Reject", reject_invitation_users_path(organization_id: u.organization_id), **tw_link_prominent_args("rounded-r-lg", without: %w[rounded-full], color: :bad)

core/app/views/users/missing_organization.html.haml
.font-bold.text-2xl.mb-8.flex.flex-row.items-center.text-pink
  %span.mr-2.text-baseline
    = heroicon "exclamation-triangle", variant: :outline
  %span
    Currently not assigned to any Organization
%p{class: "w-2/3"}
  You are currently not assigned to any organization.
  Unless you are an active member of an Organization within PROSPECT you won't be able to perform any action.

- if @user.organizations.any?
  .font-bold.text-xl.mt-8
    Click to switch to one of your organizations:
  .flex.flex-col.gap-y-4.mt-4
    - @user.organizations.each do |organization|
      = link_to switch_organization_users_path(organization_id: organization.id), method: :post do
        .ml-2.flex.flex-row.gap-x-2.hover:underline.text-primary
          = heroicon "arrow-right", variant: :solid
          = organization.to_s

- if @user.invitations.any?
  .font-bold.text-xl.mt-8
    You are invited into those organizations:
  - @user.invitations.each do |inv|
    .w-full.grid.grid-cols-6.gap-3.ml-2.mt-4.text-lg
      .organization-name{class: "col-span-3"}
        = inv.organization.name
      %span.flex.ml-4.cursor-pointer.hover:text-primary.text-sm
        = link_to "Accept", accept_invitation_users_path(organization_id: inv.organization_id), **tw_link_prominent_args("rounded-l-lg", without: %w[rounded-full])
        = link_to "Reject", reject_invitation_users_path(organization_id: inv.organization_id), **tw_link_prominent_args("rounded-r-lg", without: %w[rounded-full], color: :bad)

core/app/views/users/new.html.haml
- content_for :page_title do
  -  if Current.user.admin?
    = "Invite New User"
  - else
    = "Invite New User to #{Current.organization}"

= form_for @user, url: users_path, method: :post do |f|

  .wrapper{class: "w-1/2"}

    - if @user.errors.any?
      %ul.text-sm.mb-6.text-pink
        - @user.errors.to_a.each do |e|
          %li= e
    .field
      = f.text_field :email, placeholder: :email, required: true, **tw_text_input_args("w-full")
    .field.mt-4
      = f.select :priv_template, Privilege::TEMPLATE_NAMES, {}, **tw_select_input_args("w-full")
    - if Current.user.admin?
      .field.mt-4
        = f.collection_select :organization_id, Organization.default_order, :id, :to_s, {}, **tw_select_input_args("w-full")
    - else
      = f.hidden_field :organization_id
    .field.mt-10
      = f.submit "Invite", **tw_submit_prominent_args

core/app/views/users/show.html.haml
= content_for :page_actions do
  .flex
    - if policy(@user).update?
      %span.ml-4.cursor-pointer.text-primary
        = link_to edit_user_path(@user), title: "Edit" do
          = heroicon "pencil-square"
    - if policy(@user).toggle_archive?
      %span.ml-4.cursor-pointer.text-primary
        - title = if @user.archived?
          - "Reactivate"
        - else
          - @user.invited? ? "Delete" : "Archive"

        = link_to toggle_archive_user_path(@user), data: {turbo_method: :post}, title: title do
          - if @user.archived?
            = heroicon "archive-box-x-mark"
          - else
            = heroicon "archive-box-arrow-down"

%table.table-auto.border-spacing-y-5.border-separate
  - %i[email admin state created_at active_at archived_at].each do |attr|
    %tr
      %th.text-left.pr-5
        = attr.to_s.humanize
      %td
        = @user.public_send attr
  %tr
    %th.text-left.pr-5
      Organization
    %td
      = @user.current_organization_user.to_s_org_role
  %tr
    %th.text-left.pr-5
      Memberships
    %td
      = @user.active_organization_users.where.not(organization_id: @user.organization_id).map(&:to_s_org_role).join(", ")
  %tr
    %th.text-left.pr-5
      Invitations
    %td
      = @user.invitations.map(&:to_s_org_role).join(", ")
  - if show_invitation_url?(@user)

    %tr
      %th.text-left.pr-5
        Invitation-URL
        %p.text-xs{class: "text-grey-3"}
          Only visible 5 minutes after invitation. Please only use, in case email did't go through.
      %td{class: "font-mono"}
        = invitation_users_url invite_code: @user.invite_code
  %tr
    %th.text-left.pr-5
      Assigned Privileges
    %td
      %ul
        - OrganizationUser.where(user: @user).each do |ou|
          %li
            %b= ou.organization.name
            %ul
              - ou.privileges.each do |p|
                %li{title: t("privileges.docu.#{p.name}")}= p.name
  %tr
      

core/app/views/users/welcome.html.haml
.flex.flex-col.items-center
  = image_tag Rails.application.config.theme[:logo], class: "h-20"
  %p.mt-5
  %span.font-semibold.mb-10
    -# TODO: theme config translations?
    - t('.subtitle') # will not render, but I18n would complain if not used ;)
    = Rails.application.config.theme[:title]
  - unless current_user
    = render "session/form"

    #forgot_password.my-3
    = link_to "Forgot Password?", new_password_reset_path, {class: "text-primary hover:underline" }

    - if Rails.application.config.google_auth
      = link_to auth_at_provider_path(provider: :google), class: "mt-5" do
        = image_tag 'sign_in_with_google.svg', alt: t('users.welcome.login_with_google')
    - if Rails.application.config.ms_auth
      = link_to auth_at_provider_path(provider: :microsoft), class: "mt-5" do
        = image_tag 'ms_symbollockup_signin_light.svg', alt: t('users.welcome.login_with_microsoft')