core/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  mount Rswag::Ui::Engine => "/api-docs"
  mount Api::Base, at: "/api"

  # Defines the root path route ("/")
  root "users#welcome"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :users, except: %i[destroy] do
    get :me, on: :collection
    get "me/missing_organization", on: :collection, to: "users#missing_organization"
    get :logout, on: :collection, to: "session#logout_user"
    post :logout, on: :collection, to: "session#logout_user"
    get :invitations, on: :collection
    get :accept_invitation, on: :collection
    get :reject_invitation, on: :collection
    get "invitation/:invite_code", on: :collection, to: "users#invitation", as: "invitation"
    post "register/:invite_code", on: :collection, to: "users#register", as: "register"
    post :toggle_archive, on: :member
    get :accept_terms, on: :collection
    post :accept_terms, on: :collection
    get :switch_organization, on: :collection
    get :resend_invitation, on: :member
  end

  resources :organization_users do
    resources :privileges, only: [:index] do
      put :update, on: :collection
    end
  end

  resources :password_resets, only: %i[new create edit update]

  post "login_local" => "session#create", as: :login_local

  # oauth
  post "session/callback"
  get  "session/callback"
  get  "session/:provider" => "session#oauth", as: :auth_at_provider
  get  "oauth/callback/microsoft" => "session#callback", defaults: { provider: "microsoft" }

  resources :sources, only: %i[show destroy] do
    get :show_secret
    get :dynamic_form_template
    get :dynamic_form, on: :collection
    post :dynamic_form_submit, on: :collection
    get :view_data
    post :manual_upload
    post :trigger_now
    get :edit_project
    post :update_project
    get "public_recorded/:code", on: :collection,
                                 to: "sources#public_recorded", as: :public_recorded
    post "public_recorded_upload/:code", on: :collection,
                                         to: "sources#public_recorded_upload", as: :public_recorded_upload
    post :reprocess
    post :delete_data_and_imports
    get :csv_update
    post :csv_update_submit
    get :backfill
    get :backfill_completely
    post :backfill_from_date

    resources :imports, only: :index
  end

  resources :projects do
    resources :visibilities, except: :index, shallow: true
    get :view_data
    get :view_data_rbf

    # /sources/dynamic_form
    get :dynamic_form, on: :collection
    post :dynamic_form_submit, on: :collection
  end

  resources :build_source, only: %i[show update], controller: "sources/build"

  resources :imports, only: %i[show destroy] do
    get :download
    post :reprocess
  end

  resources :encrypted_blob

  get "demo" => "demo#index"
  get "demo/show" => "demo#show"
  get "demo/wrap_key" => "demo#wrap_key"
  post "demo/post_key" => "demo#post_key"
  post "demo/ajax_test" => "demo#ajax_test"
  get "demo/easy_web_crypto" => "demo#easy_web_crypto"

  resources :analytics, only: %i[index show] do
    get "grafana_new/:type", on: :collection, to: "analytics#grafana_new", as: :grafana_new
    get "preview/:board_uid", on: :collection, to: "analytics#preview", as: :preview
  end

  resources :docs, only: %i[index show]

  get "exports" => "exports#index"
  get "exports/export"
  get "exports/export_form"

  match "ping", to: "status#ping", via: %i[get post]

  get "organizations/mine"
  resources :organizations, except: %i[new create] do
    get :show_token
  end

  get "shared_keys_vault/edit" => "shared_keys_vault#edit"
  post "shared_keys_vault/create" => "shared_keys_vault#create"
  post "shared_keys_vault/delete" => "shared_keys_vault#delete"

  resources :rbf_claims do
    get :summary, on: :member
    get :show_do_data_collection, on: :member
    get :print_submitted, on: :member
    get :show_do_assign_verifiers, on: :member
    get :show_do_verification, on: :member
    get :download_verification_csv, on: :member
    get :show_do_payment, on: :member
    get :show_paid_out, on: :member
    get :show_verification_result, on: :member
    get :show_print_voucher, on: :member
    get :print_voucher, on: :member

    post :do_data_collection, on: :member
    post :do_data_collection_add_all, on: :member
    post :do_assign_verifiers, on: :member
    post :do_verification, on: :member
    post :do_device_verification, on: :member
    post :do_payment, on: :member
    post :do_sample_secondary_verification, on: :member

    get :device_details, on: :member
    get :device_claim, on: :member
    post "event/:event", on: :member, to: "rbf_claims#event", as: :event
    get "download/:type", on: :member, to: "rbf_claims#download", as: :download
  end

  resources :rbf_dashboard, only: :index do
    get :rbf_products, on: :collection
    post :setup_project, on: :collection
    post :add_agent, on: :collection
    post :toggle_agent, on: :collection
  end
end

core/app/controllers/exports_controller.rb
# frozen_string_literal: true

class ExportsController < ApplicationController
  @header_section = "Export"

  def index
    @source_id = clean_source_id_param
    @source = Source.find_by id: @source_id

    @page_title = if @source
                    t(".data_export_source", source: @source.to_s)
                  else
                    t(".data_export")
                  end

    @data_categories =
      Current.organization.data_categories_counts(source_id: @source_id)
    @custom_views =
      Current.organization.custom_views_counts(source_id: @source_id)

    authorize :exports
  end

  def export_form
    authorize :exports
    source_id = clean_source_id_param

    source = Source.find(source_id)
    @export_name = source.to_s_download

    # HACK: hack hack hack hack
    # TODO: fix this
    # UECCC form insert shs/meters and payments_ts data
    # and we magically know, that those tables are connected
    # via the account_external_id column

    shs_or_meters = Data::Meters.where(source_id: source.id).map(&:serializable_hash).presence ||
                    Data::SHS.where(source_id: source.id).map(&:serializable_hash).presence
    payments = Data::PaymentsTs.where(source_id: source.id).map(&:serializable_hash)

    result = [shs_or_meters, payments].flatten.group_by { |obj| obj["account_external_id"] }.to_h.map do |_account, data|
      data.reduce({}, :deep_merge)
    end

    form = DynamicForm.find(source.details["form"].to_i)
    result = Ueccc::FormBuilder.custom_ueccc_mapping(form, %w[meters payments_ts], result)

    @data = {}
    @header = result.map(&:keys).flatten.uniq - ["custom"]
    len = result.count
    result.each_with_index do |row, i|
      custom = JSON.parse(row.delete("custom") || "{}")
      row.merge(custom).each do |key, val|
        (@header << key).uniq!
        @data[key] ||= Array.new(len)
        @data[key][i] = val
      end
    end

    respond_to do |format|
      format.csv do
        full_csv = CSV.generate do |csv|
          csv << @header
          @data.values.transpose.each do |row|
            csv << row
          end
        end
        send_data full_csv, filename: "prospect_#{@export_name}.csv"
      end
      format.xlsx do
        # the rest happens in export.xlsx.axlsx
        response.headers["Content-Disposition"] = "attachment; filename=\"prospect_#{@export_name}.xlsx\""
      end
    end
  end

  def export
    authorize :exports
    @data_category = params[:data_category].presence
    @custom_view = params[:custom_view].presence
    source_id = clean_source_id_param

    raise "can only live with either data_category or custom_view!" if @data_category && @custom_view

    @export_name = [@data_category, @custom_view].compact.first

    result = if @data_category
               Current.organization.all_for_category(@data_category, source_id:)
             elsif @custom_view
               Current.organization.all_for_custom_view(@custom_view, source_id:)
             else
               raise "either data_category or custom_view - one should be given!"
             end

    @data = {}
    @header = result.fields - ["custom"]
    len = result.count
    result.each_with_index do |row, i|
      custom = JSON.parse(row.delete("custom") || "{}")
      row.merge(custom).each do |key, val|
        (@header << key).uniq!
        @data[key] ||= Array.new(len)
        @data[key][i] = val
      end
    end

    respond_to do |format|
      format.csv do
        full_csv = CSV.generate do |csv|
          csv << @header
          @data.values.transpose.each do |row|
            csv << row
          end
        end
        send_data full_csv, filename: "prospect_#{@export_name}.csv"
      end
      format.xlsx do
        # the rest happens in export.xlsx.axlsx
        response.headers["Content-Disposition"] = "attachment; filename=\"prospect_#{@export_name}.xlsx\""
      end
    end
  end
end

core/app/views/exports/index.html.haml
- if @source
  = content_for :breadcrumbs do
    = render "breadcrumb" do
      = link_to "Import", projects_path
    = render "breadcrumb" do
      = link_to @source.project
    = render "breadcrumb" do
      = link_to @source

.mb-4
  All the data available to you.
  The data can be downloaded as CSV or XLSX as well as through our API.
  Check the Docs to see more information about the meaning of each column.

%div{"data-controller": "modal", "data-action": "close-modal@window->modal#close open-modal@window->modal#open"}
  %dialog.p-8.rounded-lg{class: "backdrop:bg-black/80", "data-modal-target": "dialog"}
    %div{id: :progress} Downloading CSV

- if @source && @source.adapter.try(:dynamic_form)
  .font-bold.text-xl.mt-8.mb-4
    Dynamic Forms
  - count = Postgres::DataTable.ar(@source.data_category, @source.organization).where(source_id: @source_id).limit(Organization::COUNT_LIMIT).count
  .w-full.flex.flex-row.py-3
    - zero_class = count.zero? ? "text-grey-3" : nil
    %div{class: "basis-2/3 font-semibold #{zero_class}"}
      = @source.adapter.dynamic_form.to_s
    %div{class: "basis-1/3 flex flex-row"}
      %div{class: "basis-1/3 #{zero_class}"}
        - if count >= Organization::COUNT_LIMIT
          = "> #{Organization::COUNT_LIMIT}"
        - else
          = count
      %div{class: "basis-2/3 flex justify-end"}
        - if zero_class
          .ml-12{class: zero_class}
            csv
          .ml-3{class: zero_class}
            xlsx
          .ml-3.whitespace-nowrap{class: zero_class}
            decrypted csv
        - else
          %span.text-primary.cursor-pointer.ml-12.hover:underline
            = link_to "csv", exports_export_form_path(format: :csv, source_id: @source_id)
          %span.text-primary.cursor-pointer.ml-3.hover:underline
            = link_to "xlsx", exports_export_form_path(format: :xlsx, source_id: @source_id)
          - if Current.organization.encryption_keys?
            - dl_link = "downloadCSV('#{exports_export_form_path(format: :csv, source_id: @source_id)}')"
            %button.whitespace-nowrap.text-primary.cursor-pointer.ml-3.hover:underline{ onclick: "#{dl_link}" } decrypted csv

.font-bold.text-xl.mt-8.mb-4
  Generic Format

- @data_categories.each do |dc, count|
  .w-full.flex.flex-row.py-3
    - zero_class = count.zero? ? "text-grey-3" : nil
    %div{class: "basis-2/3 font-semibold #{zero_class}"}
      = dc
    %div{class: "basis-1/3 flex flex-row"}
      %div{class: "basis-1/3 #{zero_class}"}
        - if count >= Organization::COUNT_LIMIT
          = "> #{Organization::COUNT_LIMIT}"
        - else
          = count
      %div{class: "basis-1/3"}
        %span{class: "hover:underline text-primary/70"}= link_to "-> Docs", doc_path(dc), target: "_blank"
      %div{class: "basis-1/3 flex justify-end"}
        - if zero_class
          .ml-6{class: zero_class}
            csv
          .ml-3{class: zero_class}
            xlsx
          .ml-3.whitespace-nowrap{class: zero_class}
            decrypted csv
        - else
          %span.text-primary.cursor-pointer.ml-6.hover:underline
            = link_to "csv", exports_export_path(data_category: dc, format: :csv, source_id: @source_id)
          %span.text-primary.cursor-pointer.ml-3.hover:underline
            = link_to "xlsx", exports_export_path(data_category: dc, format: :xlsx,  source_id: @source_id)
          - if Current.organization.encryption_keys?
            - dl_link = "downloadCSV('#{exports_export_path(data_category: dc, format: :csv,  source_id: @source_id)}')"
            %button.whitespace-nowrap.text-primary.cursor-pointer.ml-3.hover:underline{ onclick: "#{dl_link}" } decrypted csv

- if @custom_views.present?
  .font-bold.text-xl.mt-8.mb-4
    Custom Format
  - @custom_views.each do |cv, count|
    .w-full.flex.flex-row.py-3
      - zero_class = "text-grey-3" if count.zero?
      %div{class: "basis-2/3 font-semibold #{zero_class}"}
        = cv
      %div{class: "basis-1/3 flex flex-row"}
        %div{class: "basis-1/3 #{zero_class}"}
          - if count >= Organization::COUNT_LIMIT
            = "> #{Organization::COUNT_LIMIT}"
          - else
            = count
        %div{class: "basis-2/3 flex justify-end"}
          - if zero_class
            .ml-12{class: zero_class}
              csv
            .ml-3{class: zero_class}
              xlsx
          - else
            %span.text-primary.cursor-pointer.ml-12.hover:underline
              = link_to "csv", exports_export_path(custom_view: cv, format: :csv, source_id: @source_id)
            %span.text-primary.cursor-pointer.ml-3.hover:underline
              = link_to "xlsx", exports_export_path(custom_view: cv, format: :xlsx, source_id: @source_id)

:javascript
  function downloadCSV(url) {
    if (!window.vault.is_open()) {
      window.vault.openModal(() => { downloadCSV(url) })
      return
    }
    const progress = window.document.getElementById("progress");
    progress.innerText = "Downloading CSV"
    window.dispatchEvent(new CustomEvent("open-modal"))
    fetch(url)
      .then(response => {
        // Ensure the request was successful
        if (!response.ok) {
          throw new Error(`Network response was not ok ${response.statusText}`);
        }
        return response.blob();
      })
      .then(blob => {
        parseCSVFromBlobAndDecrypt(blob);
      })
      .catch(error => {
        console.error('There was an error downloading the CSV file:', error);
      });
  }

  function downloadBlobasCSV(obj) {
    const csvData = new Blob([Papa.unparse(obj.data)], { type: 'text/csv;charset=utf-8;' });
    const url = window.URL.createObjectURL(csvData);
    const a = document.createElement('a');

    a.style.display = 'none';
    a.href = url;
    // Specify filename to download as
    a.download = 'data.csv';
    document.body.appendChild(a);
    a.click();
    window.URL.revokeObjectURL(url);
  }

  async function decryptCSVcolumns(csv) {
    // Assuming the first row contains column headers
    const progress = window.document.getElementById("progress");
    const count = csv.data[0].filter((h) => {return h.endsWith('_e')}).length * csv.data.length;
    let i = 1;
    if (csv.data.length > 0) {
      for (const [Yindex, header] of csv.data[0].entries()) {
        if (!header.endsWith("_e")) { continue; }

        csv.data[0][Yindex] = header.slice(0, -2)

        for (const row of csv.data.slice(1)) {
          progress.innerText = `Decrypting ${i}/${count}`
          i++;
          row[Yindex] = await window.vault.decryptMessage(row[Yindex])
        }
      }
      window.dispatchEvent(new CustomEvent("close-modal"))
      downloadBlobasCSV(csv);
    }
  }

  async function parseCSVFromBlobAndDecrypt(blob) {
    const reader = new FileReader();
    reader.onload = (event) => {
      const csvText = event.target.result;
      Papa.parse(csvText, {
        complete: decryptCSVcolumns,
        error: (error) => {
          console.error('Error parsing CSV:', error);
        }
      });
    };
    reader.onerror = (error) => {
      console.error('Error reading CSV blob:', error);
    };
    reader.readAsText(blob);
  }