core/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  mount Rswag::Ui::Engine => "/api-docs"
  mount Api::Base, at: "/api"

  # Defines the root path route ("/")
  root "users#welcome"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :users, except: %i[destroy] do
    get :me, on: :collection
    get "me/missing_organization", on: :collection, to: "users#missing_organization"
    get :logout, on: :collection, to: "session#logout_user"
    post :logout, on: :collection, to: "session#logout_user"
    get :invitations, on: :collection
    get :accept_invitation, on: :collection
    get :reject_invitation, on: :collection
    get "invitation/:invite_code", on: :collection, to: "users#invitation", as: "invitation"
    post "register/:invite_code", on: :collection, to: "users#register", as: "register"
    post :toggle_archive, on: :member
    get :accept_terms, on: :collection
    post :accept_terms, on: :collection
    get :switch_organization, on: :collection
    get :resend_invitation, on: :member
  end

  resources :organization_users do
    resources :privileges, only: [:index] do
      put :update, on: :collection
    end
  end

  resources :password_resets, only: %i[new create edit update]

  post "login_local" => "session#create", as: :login_local

  # oauth
  post "session/callback"
  get  "session/callback"
  get  "session/:provider" => "session#oauth", as: :auth_at_provider
  get  "oauth/callback/microsoft" => "session#callback", defaults: { provider: "microsoft" }

  resources :sources, only: %i[show destroy] do
    get :show_secret
    get :dynamic_form_template
    get :dynamic_form, on: :collection
    post :dynamic_form_submit, on: :collection
    get :view_data
    post :manual_upload
    post :trigger_now
    get :edit_project
    post :update_project
    get "public_recorded/:code", on: :collection,
                                 to: "sources#public_recorded", as: :public_recorded
    post "public_recorded_upload/:code", on: :collection,
                                         to: "sources#public_recorded_upload", as: :public_recorded_upload
    post :reprocess
    post :delete_data_and_imports
    get :csv_update
    post :csv_update_submit
    get :backfill
    get :backfill_completely
    post :backfill_from_date

    resources :imports, only: :index
  end

  resources :projects do
    resources :visibilities, except: :index, shallow: true
    get :view_data
    get :view_data_rbf

    # /sources/dynamic_form
    get :dynamic_form, on: :collection
    post :dynamic_form_submit, on: :collection
  end

  resources :build_source, only: %i[show update], controller: "sources/build"

  resources :imports, only: %i[show destroy] do
    get :download
    post :reprocess
  end

  resources :encrypted_blob

  get "demo" => "demo#index"
  get "demo/show" => "demo#show"
  get "demo/wrap_key" => "demo#wrap_key"
  post "demo/post_key" => "demo#post_key"
  post "demo/ajax_test" => "demo#ajax_test"
  get "demo/easy_web_crypto" => "demo#easy_web_crypto"

  resources :analytics, only: %i[index show] do
    get "grafana_new/:type", on: :collection, to: "analytics#grafana_new", as: :grafana_new
    get "preview/:board_uid", on: :collection, to: "analytics#preview", as: :preview
  end

  resources :docs, only: %i[index show]

  get "exports" => "exports#index"
  get "exports/export"
  get "exports/export_form"

  match "ping", to: "status#ping", via: %i[get post]

  get "organizations/mine"
  resources :organizations, except: %i[new create] do
    get :show_token
  end

  get "shared_keys_vault/edit" => "shared_keys_vault#edit"
  post "shared_keys_vault/create" => "shared_keys_vault#create"
  post "shared_keys_vault/delete" => "shared_keys_vault#delete"

  resources :rbf_claims do
    get :summary, on: :member
    get :show_do_data_collection, on: :member
    get :print_submitted, on: :member
    get :show_do_assign_verifiers, on: :member
    get :show_do_verification, on: :member
    get :download_verification_csv, on: :member
    get :show_do_payment, on: :member
    get :show_paid_out, on: :member
    get :show_verification_result, on: :member
    get :show_print_voucher, on: :member
    get :print_voucher, on: :member

    post :do_data_collection, on: :member
    post :do_data_collection_add_all, on: :member
    post :do_assign_verifiers, on: :member
    post :do_verification, on: :member
    post :do_device_verification, on: :member
    post :do_payment, on: :member
    post :do_sample_secondary_verification, on: :member

    get :device_details, on: :member
    get :device_claim, on: :member
    post "event/:event", on: :member, to: "rbf_claims#event", as: :event
    get "download/:type", on: :member, to: "rbf_claims#download", as: :download
  end

  resources :rbf_dashboard, only: :index do
    get :rbf_products, on: :collection
    post :setup_project, on: :collection
    post :add_agent, on: :collection
    post :toggle_agent, on: :collection
  end
end

core/app/controllers/rbf_claims_controller.rb
# frozen_string_literal: true

class RbfClaimsController < ApplicationController
  # after_action :verify_authorized

  @header_section = "RBF"

  def index
    authorize :rbf_claim
    base_query = RbfClaim.for_index(Current.organization).default_order

    see_all_privs = %w[rbf_claim.show_claims_full rbf_claim.show_claims_status rbf_claim.show_claims_minimal]

    @claims = if current_user.can_any?(see_all_privs)
                base_query
              elsif current_user.can? "rbf_claim.do_verification"
                base_query.verification.select { current_user.in? _1.rbf_claim_verifiers }
              else
                base_query.none
              end
  end

  def show
    @claim = authorize RbfClaim.find params[:id]
  end

  def new
    @claim = RbfClaim.new rbf_claim_template_id: params[:rbf_claim_template_id],
                          organization: Current.organization
  end

  def create
    @claim = RbfClaim.new organization: Current.organization,
                          rbf_claim_template_id: params.dig(:rbf_claim, :rbf_claim_template_id)
    authorize @claim

    if @claim.save
      redirect_to @claim, notice: "Claim created" # rubocop:disable Rails/I18nLocaleTexts
    else
      render :new, status: :unprocessable_content, alert: @claim.errors.full_messages.to_sentence
    end
  end

  def summary
    @claim = authorize RbfClaim.find params[:id]
  end

  def show_do_data_collection
    @claim = authorize RbfClaim.find params[:id]
  end

  def show_do_assign_verifiers
    @claim = authorize RbfClaim.find params[:id]
    @candidates = @claim.
                  verifying_organization.active_users.
                  select { _1.can? "rbf_claim.do_verification", in_organization: @claim.verifying_organization }
  end

  def show_do_verification
    @claim = authorize RbfClaim.find params[:id]
  end

  def show_do_payment
    @claim = authorize RbfClaim.find params[:id]
  end

  def show_paid_out
    @claim = authorize RbfClaim.find params[:id]
  end

  def show_verification_result
    @claim = authorize RbfClaim.find params[:id]
  end

  def show_print_voucher
    @claim = authorize RbfClaim.find params[:id]
  end

  def print_voucher
    @claim = authorize RbfClaim.find params[:id]
    render :print_voucher, layout: false
  end

  def do_data_collection
    @claim = authorize RbfClaim.find params[:id]
    @claim.do_data_collection data_collection_claim_params.to_h, mode: params[:mode]
    redirect_to @claim, notice: "Devices for submission updated" # rubocop:disable Rails/I18nLocaleTexts
  end

  def do_data_collection_add_all
    @claim = authorize RbfClaim.find params[:id]
    @claim.do_data_collection_add_all
    redirect_to @claim, notice: "All eligible devices added to claim" # rubocop:disable Rails/I18nLocaleTexts
  end

  def data_collection_claim_params
    params.permit(claim: {})[:claim]
  end

  def do_assign_verifiers
    @claim = authorize RbfClaim.find params[:id]
    @claim.verification_users_ids = params.dig(:rbf_claim, :verification_users_ids)
    redirect_to @claim, notice: "Users for verification assigned" # rubocop:disable Rails/I18nLocaleTexts
  end

  def do_device_verification
    @claim = authorize RbfClaim.find params[:id]
    @claim.do_device_verification uid: params[:uid],
                                  state_rejection_combined: params[:rbf_device_claim][:state_rejection_combined],
                                  reviewer_comment: params[:rbf_device_claim][:reviewer_comment]
    if params[:commit].to_s.include?("next") && params[:next_device].present?
      redirect_to device_details_rbf_claim_path(@claim, uid: params[:next_device], mode: :existing)
    elsif params[:commit].to_s.include?("back")
      redirect_to rbf_claim_path(@claim)
    else
      redirect_to device_details_rbf_claim_path(@claim, uid: params[:uid], mode: :existing)
    end
  end

  def print_submitted
    @claim = authorize RbfClaim.find params[:id]
    render :print_submitted, layout: false
  end

  def download_verification_csv
    @claim = authorize RbfClaim.find params[:id]

    fields = [
      :submission_category,
      :submission_comment,
      :verification_category,
      :state,
      :rejection_category,
      :reviewer_comment,
      :device_category,
      :claimed_subsidy,
      :claimed_incentive,
      "claimed_devices_data->'purchase_date'",
      "claimed_devices_data->'model'",
      "claimed_devices_data->'manufacturer'",
      "claimed_devices_data->'serial_number'",
      "claimed_devices_data->'custom'->'serial_number_2'",
      "claimed_devices_data->'custom'->'customer_firstname_e'",
      "claimed_devices_data->'custom'->'customer_surname_e'",
      "claimed_devices_data->'customer_id_type'",
      "claimed_devices_data->'customer_id_number_e'",
      "claimed_devices_data->'customer_gender'",
      "claimed_devices_data->'custom'->'is_household_head'",
      "claimed_devices_data->'customer_phone_e'",
      "claimed_devices_data->'customer_phone_2_e'",
      "claimed_devices_data->'customer_location_area_1'",
      "claimed_devices_data->'customer_location_area_2'",
      "claimed_devices_data->'customer_location_area_3'",
      "claimed_devices_data->'customer_location_area_4'",
      "claimed_devices_data->'customer_location_area_5'",
      "claimed_devices_data->'payment_plan_type'",
      "claimed_devices_data->'payment_plan_days'",
      "claimed_devices_data->'payment_plan_down_payment'",
      "claimed_devices_data->'account_external_id'"
    ].map(&:to_s)

    pluck_args = fields.map { _1.include?("->") ? Arel.sql(_1) : _1 }
    headers = fields.map do |f|
      f.gsub("claimed_devices_data", "device").gsub("'custom'->", "").gsub("'", "").gsub("->", "_")
    end

    plucked = @claim.rbf_device_claims.pluck(*pluck_args)

    data = CSV.generate do |csv|
      csv << headers
      plucked.each { csv << _1 }
    end

    send_data data
  end

  def do_verification
    @claim = authorize RbfClaim.find params[:id]
    @claim.do_verification params[:claim]
    render :show_do_verification, notice: "Verified Devices updated"
    # redirect_to @claim, notice: "Verified Devices updated"
  end

  def do_sample_secondary_verification
    @claim = authorize RbfClaim.find params[:id]
    @claim.sample_for_secondary_verification!
    redirect_to @claim, notice: "Devices sampled for secondary validation" # rubocop:disable Rails/I18nLocaleTexts
  end

  def do_payment
    @claim = authorize RbfClaim.find params[:id]
    @claim.do_payment params[:claim]
    redirect_to @claim, notice: "Payment Information updated" # rubocop:disable Rails/I18nLocaleTexts
  end

  def device_details
    @claim = authorize RbfClaim.find params[:id]
    @verification_mode = @claim.verification? && authorize(@claim, :do_verification?)
    @device_data = @claim.device_data params[:uid], mode: params[:mode].to_sym
  end

  def device_claim
    @claim = authorize RbfClaim.find params[:id]
    @device_claim = @claim.rbf_device_claims.find(params[:rbf_device_claim_id])
  end

  def download
    typ = params[:type]
    @claim = authorize RbfClaim.find params[:id]
    header = @claim.claimed_data["data"].first.keys
    full_csv = CSV.generate do |csv|
      csv << header
      sample_len = @claim.claimed_data["data"].count / 10
      sample_half = sample_len / 2

      stuff = case typ
              when "all", "desk"
                @claim.claimed_data["data"]
              when "phone"
                @claim.claimed_data["data"].sample(sample_len, random: Random.new(@claim.id))[0..sample_half]
              when "field"
                @claim.claimed_data["data"].sample(sample_len, random: Random.new(@claim.id))[(sample_half + 1)..]
              end

      stuff.each do |r|
        csv << header.map { r[_1] }
      end
    end
    send_data full_csv, filename: "claim_#{@claim.id}_#{typ}.csv"
  end

  def event
    @claim = authorize RbfClaim.find params[:id]
    ev = @claim.aasm.events(possible: true).find { |e| e.to_s == params[:event] }

    if @claim.public_send "may_#{ev}?"
      @claim.public_send "#{ev}!"
      redirect_to @claim, notice: "Claim moved to #{@claim.reload.aasm_state.titleize}"
    else
      redirect_to @claim, alert: "You can not perform this action at the moment" # rubocop:disable Rails/I18nLocaleTexts:
    end
  end
end

core/app/views/rbf_claims/_collect_autogenerated.html.haml
= form_for @claim, url: do_data_collection_rbf_claim_path(mode: :add), method: :post do |f|
  .grid.grid-cols-2.mt-8.mb-8
    .font-bold.text-xl
      Collect Devices to include in claim
    .w-full
      = f.submit "Update Claimed Devices", data: { turbo_disable_with: "Updating ...",  turbo_frame: "_top" }, **tw_submit_prominent_args

  - data = @claim.query_batch.reject{ _1[:previous_device_claim] }

  %div{data: {controller: "tabulator-local checkbox-select-group" }}
    .w-full.flex.flex-row.justify-between
      %div
        %input#toggle_all_add{ type: :checkbox,
                    data: { checkbox_select_group_target: "checkboxGroup",
                    action: "change->checkbox-select-group#toggleGroup",
                    checkbox_group: "add" }}
        %label.text-grey-3{for: :toggle_all_add, class: "hover:text-grey-4"}
          Toggle All (only this page)
      %div
        = link_to "Add all", do_data_collection_add_all_rbf_claim_path,
                  data: {turbo_method: :post, turbo_disable_with: "Submitting ...", turbo_frame: "_top", controller: "disable-link", "disable-link-msg-value": "Submitting... Please be patient"},
                  **tw_link_prominent_args
    %table#collect_autogenerated_table{ data: {"tabulator-local-target": "table"}}
      %thead
        %tr
          %th{"tabulator-formatter": :html, "tabulator-headerFilter": :input}
            Device
          %th{"tabulator-formatter": :html, "tabulator-titleFormatter": :html}
            Submit
          %th{"tabulator-formatter": :html, "tabulator-headerFilter": :input}
            Comment
      %tbody
        - data.each_with_index do |d, i|
          - uid = d.dig(:trust_trace, :uid)
          %tr
            %td
              %span{class: "hover:underline text-primary/70"}
                - s = d.dig(:device).slice(:manufacturer, :model, :serial_number).values.join(" / ")
                = link_to s, device_details_rbf_claim_path(uid: uid, mode: :add), target: "_blank"
            %td
              = check_box_tag "claim[#{uid}]add", "add", d[:existing_device_claim].present?,
                              data: { checkbox_select_group_target: "checkbox",
                                      action: "change->checkbox-select-group#refresh",
                                      checkbox_group: "add" }
            %td
              = text_field_tag "claim[#{uid}]submission_comment", d[:existing_device_claim]&.submission_comment, class: "w-full"

core/app/views/rbf_claims/_collect_rejected.html.haml
= form_for @claim, url: do_data_collection_rbf_claim_path(mode: :resubmission), method: :post do |f|
  .grid.grid-cols-2.mt-8.mb-8
    .font-bold.text-xl
      Collect Previously rejected claims
    .w-full
      = f.submit "Update Resubmitted Devices", data: { turbo_disable_with: "Updating ...",  turbo_frame: "_top" }, **tw_submit_prominent_args

  - data = @claim.device_claims_for_resubmission
  %div{data: {controller: "tabulator-local checkbox-select-group" }}
    %div
      %input#toggle_all_resubmission{ type: :checkbox,
                  data: { checkbox_select_group_target: "checkboxGroup",
                  action: "change->checkbox-select-group#toggleGroup",
                  checkbox_group: "resubmission" }}
      %label.text-grey-3{for: :toggle_all_resubmission, class: "hover:text-grey-4"}
        Toggle All
    %table#collect_rejected_table{ data: {"tabulator-local-target": "table" }}
      %thead
        %tr
          %th{"tabulator-formatter": :html, "tabulator-headerFilter": :input}
            Device
          %th{"tabulator-headerFilter": :input}
            Reason
          %th{"tabulator-formatter": :html}
            Submit
          %th{"tabulator-formatter": :html, "tabulator-headerFilter": :input}
            Repair Date / Comment
      %tbody
        - data.each_with_index do |d, i|
          - uid = d.trust_trace_uid
          - existing_dc = @claim.rbf_device_claims.find_by(parent_rbf_device_claim: d)
          %tr
            %td
              %span{class: "hover:underline text-primary/70"}
                = link_to d.device_s, device_details_rbf_claim_path(uid: uid, mode: :resubmission), target: "_blank"
            %td
              = d.rejection_category
              - if d.reviewer_comment
                = ": #{d.reviewer_comment}"
            %td
              = hidden_field_tag "claim[#{uid}]parent_device_claim_id", d.id
              = check_box_tag "claim[#{uid}]resubmission", "resubmission", existing_dc.present?,
                              data: { checkbox_select_group_target: "checkbox",
                                      action: "change->checkbox-select-group#refresh",
                                      checkbox_group: "resubmission" }
            %td
              - if d.rejected_broken?
                = date_field_tag "claim[#{uid}]submission_comment", existing_dc&.submission_comment, class: "w-full"
              - else
                = text_field_tag "claim[#{uid}]submission_comment", existing_dc&.submission_comment, class: "w-full"

core/app/views/rbf_claims/_collect_repossessed.html.haml
= form_for @claim, url: do_data_collection_rbf_claim_path(mode: :repossessed), method: :post do |f|
  .grid.grid-cols-2.mt-8.mb-8
    .font-bold.text-xl
      Collect Repossessed Devices which were previously approved
    .w-full
      = f.submit "Update Repossessed Devices", data: { turbo_disable_with: "Updating ...",  turbo_frame: "_top" }, **tw_submit_prominent_args

  - data = @claim.device_claims_for_repossession
  %div{data: {controller: "tabulator-local checkbox-select-group" }}
    %div
      %input#toggle_all_repossessed{ type: :checkbox,
                  data: { checkbox_select_group_target: "checkboxGroup",
                  action: "change->checkbox-select-group#toggleGroup",
                  checkbox_group: "repossessed" }}
      %label.text-grey-3{for: :toggle_all_repossessed, class: "hover:text-grey-4"}
        Toggle All
    %table#collect_reposessed_table{ data: {"tabulator-local-target": "table" }}
      %thead
        %tr
          %th{"tabulator-formatter": :html, "tabulator-headerFilter": :input, "tabulator-resizable": false}
            Device
          %th{"tabulator-formatter": :html, "tabulator-resizable": false}
            Submit
          %th{"tabulator-formatter": :html, "tabulator-headerFilter": :input, "tabulator-resizable": false}
            Comment
      %tbody
        - data.each_with_index do |d, i|
          - uid = d.trust_trace_uid
          - existing_dc = @claim.rbf_device_claims.find_by(parent_rbf_device_claim: d)
          %tr
            %td
              %span{class: "hover:underline text-primary/70"}
                = link_to d.device_s, device_details_rbf_claim_path(uid: uid, mode: :repossessed), target: "_blank"
            %td
              = hidden_field_tag "claim[#{uid}]parent_device_claim_id", d.id
              = check_box_tag "claim[#{uid}]repossessed", "repossessed", existing_dc.present?,
                              data: { checkbox_select_group_target: "checkbox",
                                      action: "change->checkbox-select-group#refresh",
                                      checkbox_group: "repossessed" }
            %td
              = text_field_tag "claim[#{uid}]submission_comment", existing_dc&.submission_comment, class: "w-full"

core/app/views/rbf_claims/index.html.haml
= content_for :page_title do
  RBF

= content_for :page_actions do
  - if Current.organization&.rbf_submitting?
    = link_to "RBF Dashboard", rbf_dashboard_index_path, **tw_link_prominent_args
  - if policy(:rbf_claim).new?
    - data_collection_claim_templates = RbfClaim.data_collection.where(organization: Current.organization).map(&:rbf_claim_template).compact
    - Current.organization.submittable_rbf_claim_templates.reject{ _1.in? data_collection_claim_templates }.each do |rct|
      = link_to "New Claim for #{rct}", new_rbf_claim_path(rbf_claim_template_id: rct.id), **tw_link_prominent_args

- action_required = @claims.select{ _1.next_possible_event_org == Current.organization }.sort_by{ _1.submitted_at || _1.created_at }
- finished = @claims.select{ _1.aasm_state.in? %w[paid_out rejected]}.sort_by(&:updated_at).reverse
- non_open_others = action_required + finished
- open_others = @claims.reject{ _1.in? non_open_others }.sort_by(&:submitted_at)

= render "tabs", titles: ["Action Required", "Open", "Finalized"] do
  = render "tab" do
    = render "claims_list", claims: action_required, table_id: :action_required
  = render "tab" do
    = render "claims_list", claims: open_others, table_id: :open_others
  = render "tab" do
    = render "claims_list", claims: finished, table_id: :finished

core/app/views/rbf_claims/show.html.haml
= content_for :page_title do
  = @claim.to_s
  .text-2xl.font-bold.mt-2
    = @claim.waiting_for_s

= content_for :page_actions do
  .flex.flex-row.gap-x-1
    - n_evn = @claim.possible_negative_event_name
    - if n_evn && @claim.organization_can_now?(n_evn, Current.organization)
      = link_to n_evn.to_s.titleize,
        event_rbf_claim_path(@claim, event: n_evn),
        data: {turbo_method: :post, turbo_frame: "_top"}, **tw_link_prominent_args(color: :bad)
    - p_evn = @claim.possible_positive_event_name
    - if p_evn && @claim.organization_can_now?(p_evn, Current.organization)
      = link_to p_evn.to_s.titleize,
        event_rbf_claim_path(@claim, event: p_evn),
        data: {turbo_method: :post, turbo_frame: "_top"}, **tw_link_prominent_args
    - if policy(@claim).do_sample_secondary_verification?
      = link_to "Sample Secondary Verification",
        do_sample_secondary_verification_rbf_claim_path(@claim),
        data: {turbo_method: :post, turbo_frame: "_top"}, **tw_link_prominent_args
    - if policy(@claim).download_verification_csv?
      %button{data: {controller: "decrypt-csv", decrypt_csv_target: "button", action: "decrypt-csv#downloadCSV",
              decrypt_csv_url_value: download_verification_csv_rbf_claim_path(@claim),
              decrypt_csv_filename_value: [@claim.code.gsub(/\W/, '-'), "_verification.csv"].join },
              class: tw_link_prominent_args[:class] }
        Download Verification CSV
    - if policy(@claim).print_submitted?
      = link_to "Print Claim", print_submitted_rbf_claim_path(@claim), **tw_link_prominent_args


- more_tabs = []
- if @claim.data_collection? && policy(@claim).do_data_collection?
  - more_tabs << ["Build Claim", :claim_action, show_do_data_collection_rbf_claim_path(@claim)]
- elsif @claim.verification?
  - if policy(@claim).do_assign_verifiers?
    - more_tabs << ["Assign Verifiers", :assign_verifiers, show_do_assign_verifiers_rbf_claim_path(@claim)]
  - if policy(@claim).do_verification?
    - more_tabs << ["Verification", :claim_action, show_do_verification_rbf_claim_path(@claim)]
- elsif @claim.approved? && policy(@claim).do_payment?
  - more_tabs << ["Print Voucher", :print_voucher, show_print_voucher_rbf_claim_path(@claim)]
  - more_tabs << ["Enter Payment", :claim_action, show_do_payment_rbf_claim_path(@claim)]
- elsif @claim.submitted_to_program? && policy(@claim).show_paid_out?
  - more_tabs << ["Show Data", :claim_action, show_paid_out_rbf_claim_path(@claim)]
- elsif @claim.paid_out?
  - more_tabs << ["Show Result", :claim_action, show_paid_out_rbf_claim_path(@claim)]
- if !@claim.data_collection? && policy(@claim).show_verification_result?
  - more_tabs << ["Verification Result", :verification_result, show_verification_result_rbf_claim_path(@claim)]


= render "tabs", titles: ["Summary", more_tabs.map(&:first)].flatten.compact do
  = render "tab" do
    = turbo_frame_tag :claim_summary, src: summary_rbf_claim_path(@claim), loading: :lazy do
      .animate-pulse.p-4.bg-grey-2.rounded-md.text-white.text-center.text-sm
        = "Loading ..."
  - more_tabs.each do |t|
    = render "tab" do
      = turbo_frame_tag t.second, src: t.third, loading: :lazy do
        .animate-pulse.p-4.bg-grey-2.rounded-md.text-white.text-center.text-sm
          = "Loading ..."

core/app/views/rbf_claims/show_do_payment.html.haml
= turbo_frame_tag :claim_action do
  .font-bold.text-xl.mt-8.mb-4
    Enter payment details
  = form_for @claim, url: do_payment_rbf_claim_path, method: :post do |f|
    - pd = @claim.verified_data
    %table.table-auto.border-spacing-y-5.border-separate
      = render "attrib_tr", title: "Amount" do
        = number_field_tag "claim[transaction_amount]", pd["transaction_amount"] || @claim.approved_immediate_payout, required: true
      = render "attrib_tr", title: "Transaction Data" do
        = date_field_tag "claim[transaction_date]", pd["transaction_date"], required: true
      = render "attrib_tr", title: "Transaction Method" do
        = text_field_tag "claim[transaction_method]", pd["transaction_method"] || "Bank", required: true
      = render "attrib_tr", title: "Transaction ID" do
        = text_field_tag "claim[transaction_id]", pd["transaction_id"], required: true

    .field.mt-10
      = f.submit "Submit Payment Information", data: { turbo_frame: "_top" }, **tw_submit_prominent_args

core/app/views/rbf_claims/show_paid_out.html.haml
= turbo_frame_tag :claim_action do
  %div{data: {controller: "tabulator-local"}}
    %table{id: "show_paid_out_table", data: {"tabulator-local-target": "table"}}
      %thead
        %tr
          %th{"tabulator-formatter": :plaintext, "tabulator-headerFilter": :input}
            = "#"
          %th{"tabulator-formatter": :html, "tabulator-headerFilter": :input}
            Device
          %th{"tabulator-formatter": :plaintext, "tabulator-headerFilter": :input}
            Category
          %th{"tabulator-formatter": :plaintext, "tabulator-headerFilter": :input}
            Method
          %th{"tabulator-formatter": :plaintext, "tabulator-headerFilter": :input}
            State
          %th{"tabulator-formatter": :plaintext, "tabulator-headerFilter": :input}
            Comment
      %tbody
        - @claim.rbf_device_claims.each_with_index do |d, i|
          - uid = d.trust_trace_uid
          %tr
            %td
              = i + 1
            %td
              %span{class: "hover:underline text-primary/70"}
                = link_to d.device_s, device_details_rbf_claim_path(uid: uid, mode: :existing), target: "_blank"
            %td
              = d.verification_category&.humanize
            %td
              = d.submission_category&.humanize
            %td
              = d.state.humanize
            %td
              = d.reviewer_comment
  -# %table.table-auto.border-spacing-y-5.border-separate.w-full
  -#   %tr
  -#     %th.text-left #
  -#     %th.text-left Device
  -#     %th.text-left Category
  -#     %th.text-left Result
  -#     %th.text-left Comment
  -#   - @claim.rbf_device_claims.each_with_index do |d, i|
  -#
  -#
  -#     %tr
  -#       %td
  -#         = i + 1
  -#       %td
  -#         %span{class: "hover:underline text-primary/70"}
  -#           = link_to d.device_s, device_details_rbf_claim_path(uid: d.trust_trace_uid, mode: :existing), target: "_blank"
  -#       %td
  -#         = d.submission_category.humanize
  -#       %td
  -#         = d.state
  -#       %td
  -#         = d.reviewer_comment

core/app/views/rbf_claims/show_print_voucher.html.haml
= turbo_frame_tag :print_voucher do
  .font-bold.text-xl.mt-8.mb-8
    Print Voucher
  = link_to 'Print', print_voucher_rbf_claim_path(@claim), target:  "_blank", **tw_link_prominent_args