core/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  mount Rswag::Ui::Engine => "/api-docs"
  mount Api::Base, at: "/api"

  # Defines the root path route ("/")
  root "users#welcome"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :users, except: %i[destroy] do
    get :me, on: :collection
    get "me/missing_organization", on: :collection, to: "users#missing_organization"
    get :logout, on: :collection, to: "session#logout_user"
    post :logout, on: :collection, to: "session#logout_user"
    get :invitations, on: :collection
    get :accept_invitation, on: :collection
    get :reject_invitation, on: :collection
    get "invitation/:invite_code", on: :collection, to: "users#invitation", as: "invitation"
    post "register/:invite_code", on: :collection, to: "users#register", as: "register"
    post :toggle_archive, on: :member
    get :accept_terms, on: :collection
    post :accept_terms, on: :collection
    get :switch_organization, on: :collection
    get :resend_invitation, on: :member
  end

  resources :organization_users do
    resources :privileges, only: [:index] do
      put :update, on: :collection
    end
  end

  resources :password_resets, only: %i[new create edit update]

  post "login_local" => "session#create", as: :login_local

  # oauth
  post "session/callback"
  get  "session/callback"
  get  "session/:provider" => "session#oauth", as: :auth_at_provider
  get  "oauth/callback/microsoft" => "session#callback", defaults: { provider: "microsoft" }

  resources :sources, only: %i[show destroy] do
    get :show_secret
    get :dynamic_form_template
    get :dynamic_form, on: :collection
    post :dynamic_form_submit, on: :collection
    get :view_data
    post :manual_upload
    post :trigger_now
    get :edit_project
    post :update_project
    get "public_recorded/:code", on: :collection,
                                 to: "sources#public_recorded", as: :public_recorded
    post "public_recorded_upload/:code", on: :collection,
                                         to: "sources#public_recorded_upload", as: :public_recorded_upload
    post :reprocess
    post :delete_data_and_imports
    get :csv_update
    post :csv_update_submit
    get :backfill
    get :backfill_completely
    post :backfill_from_date

    resources :imports, only: :index
  end

  resources :projects do
    resources :visibilities, except: :index, shallow: true
    get :view_data
    get :view_data_rbf

    # /sources/dynamic_form
    get :dynamic_form, on: :collection
    post :dynamic_form_submit, on: :collection
  end

  resources :build_source, only: %i[show update], controller: "sources/build"

  resources :imports, only: %i[show destroy] do
    get :download
    post :reprocess
  end

  resources :encrypted_blob

  get "demo" => "demo#index"
  get "demo/show" => "demo#show"
  get "demo/wrap_key" => "demo#wrap_key"
  post "demo/post_key" => "demo#post_key"
  post "demo/ajax_test" => "demo#ajax_test"
  get "demo/easy_web_crypto" => "demo#easy_web_crypto"

  resources :analytics, only: %i[index show] do
    get "grafana_new/:type", on: :collection, to: "analytics#grafana_new", as: :grafana_new
    get "preview/:board_uid", on: :collection, to: "analytics#preview", as: :preview
  end

  resources :docs, only: %i[index show]

  get "exports" => "exports#index"
  get "exports/export"
  get "exports/export_form"

  match "ping", to: "status#ping", via: %i[get post]

  get "organizations/mine"
  resources :organizations, except: %i[new create] do
    get :show_token
  end

  get "shared_keys_vault/edit" => "shared_keys_vault#edit"
  post "shared_keys_vault/create" => "shared_keys_vault#create"
  post "shared_keys_vault/delete" => "shared_keys_vault#delete"

  resources :rbf_claims do
    get :summary, on: :member
    get :show_do_data_collection, on: :member
    get :print_submitted, on: :member
    get :show_do_assign_verifiers, on: :member
    get :show_do_verification, on: :member
    get :download_verification_csv, on: :member
    get :show_do_payment, on: :member
    get :show_paid_out, on: :member
    get :show_verification_result, on: :member
    get :show_print_voucher, on: :member
    get :print_voucher, on: :member

    post :do_data_collection, on: :member
    post :do_data_collection_add_all, on: :member
    post :do_assign_verifiers, on: :member
    post :do_verification, on: :member
    post :do_device_verification, on: :member
    post :do_payment, on: :member
    post :do_sample_secondary_verification, on: :member

    get :device_details, on: :member
    get :device_claim, on: :member
    post "event/:event", on: :member, to: "rbf_claims#event", as: :event
    get "download/:type", on: :member, to: "rbf_claims#download", as: :download
  end

  resources :rbf_dashboard, only: :index do
    get :rbf_products, on: :collection
    post :setup_project, on: :collection
    post :add_agent, on: :collection
    post :toggle_agent, on: :collection
  end
end

core/app/models/import.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: imports
#
#  id                     :bigint           not null, primary key
#  error                  :string
#  ingestion_finished_at  :datetime
#  ingestion_started_at   :datetime
#  last_imported_hint     :string
#  processing_finished_at :datetime
#  processing_started_at  :datetime
#  protocol               :text
#  rows_duplicated        :integer
#  rows_failed            :integer
#  rows_inserted          :integer
#  rows_updated           :integer
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  source_id              :bigint
#
# Indexes
#
#  index_imports_on_source_id  (source_id)
#

class Import < ApplicationRecord
  include OwningOrganization

  CONTENT_TYPES = { json: "application/json", csv: "text/csv", txt: "text/plain" }.freeze

  belongs_to :source
  has_one :project, through: :source
  has_one :organization, through: :project
  has_many :encrypted_blobs, dependent: :destroy

  has_one_attached :file
  has_one_attached :recording

  delegate :organization_id, to: :project, allow_nil: false

  scope :failed, -> { where.not error: nil }
  scope :no_error, -> { where error: nil }
  scope :pending, -> { no_error.where(ingestion_started_at: nil) }
  scope :ingestion_started, -> { no_error.where.not(ingestion_started_at: nil).where(ingestion_finished_at: nil) }
  scope :ingestion_finished, -> { no_error.where.not(ingestion_finished_at: nil).where(processing_started_at: nil) }
  scope :processing_started, -> { no_error.where.not(processing_started_at: nil).where(processing_finished_at: nil) }
  scope :processing_finished, -> { no_error.where.not(processing_finished_at: nil) }
  scope :unfinished, -> { no_error.where(processing_finished_at: nil) }

  before_destroy :delete_data!
  after_commit :notify_processing

  STATES = %w[
    pending
    ingestion_started
    ingestion_finished
    processing_started
    processing_finished
  ].freeze

  STATES.each do |state_name|
    # failed scopes like: ingestion_started_failed
    scope :"#{state_name}_failed", -> { public_send(state_name).unscope(where: :error).failed }

    # state checker no error like: ingestion_started?
    define_method "#{state_name}?" do
      state == state_name
    end

    # state checker failed like: ingestion_started_failed?
    define_method "#{state_name}_failed?" do
      state == "#{state_name}_failed"
    end

    # set and persist state timestamps as now: ingestion_started!
    unless state_name == "pending" # rubocop:disable Style/Next
      define_method "#{state_name}!" do
        update! "#{state_name}_at" => Time.zone.now
      end
    end
  end

  def failed!(error_msg)
    update! error: error_msg
  end

  def no_error?
    error.nil?
  end

  def failed?
    error.present? && error != "no_data"
  end

  def no_data?
    error.present? && error == "no_data"
  end

  def step_state
    if !ingestion_started_at
      "pending"
    elsif !ingestion_finished_at
      "ingestion_started"
    elsif !processing_started_at
      "ingestion_finished"
    elsif !processing_finished_at
      "processing_started"
    else
      "processing_finished"
    end
  end

  def state
    return "no_data" if no_data?

    error_state = failed? ? "_failed" : ""
    step_state + error_state
  end

  def state_int
    STATES.index(step_state)
  end

  def state_percent
    return 0 if no_data?

    (state_int.to_f / (STATES.count - 1)) * 100
  end

  def state_int_of
    "#{state_int}/#{STATES.count - 1}"
  end

  def state_symbol
    if failed?
      "⨯"
    elsif processing_finished?
      "✔"
    else
      "…"
    end
  end

  def time_s
    "#{created_at} ... #{processing_finished_at}".strip
  end

  def notify_processing(force: false)
    unless should_process? || force
      Rails.logger.debug { "Skipped processing notification for Import #{id}" }
      return
    end

    FaktoryPusher.push source.data_schema, faktory_worker_args

    notify_rbf_post_processing
  end

  def notify_rbf_post_processing
    return unless organization.rbf_submitting?

    ImportPostProcessingWorker.enqueue_for_rbf_import self
  end

  def requires_recording?
    source.adapter.try(:requires_recording?) && !recording.attached?
  end

  def should_process?
    !failed? && ingestion_finished? && file.attached? && !requires_recording?
  end

  def faktory_worker_args
    [
      id, # the id of the import job, used to track progress / error
      source_id, # source id to note on data, so we can track origin / calculate visibility
      file.key, # basically the filename in minio
      file.content_type, # file format, in mime type notation - helps to parse properly
      source.data_origin, # to help build uids, eg. [organization_id]_[data_origin]_[some_external_id]
      source.project.organization_id # to help build uids, eg. [organization_id]_[data_origin]_[some_external_id]
    ]
  end

  def push_manual_update!
    return if failed? || ingestion_finished? || !file.attached? || !persisted?

    FaktoryPusher.push "generic", faktory_worker_args

    # skip the normal pushing callback
    update_column :ingestion_finished_at, Time.zone.now # rubocop:disable Rails/SkipsModelValidations
  end

  def reprocess!
    update! processing_finished_at: nil, processing_started_at: nil, error: nil
  end

  def delete_data!
    dts = Postgres::DataTable.all.select do |dt|
      (%w[import_id] - dt.columns.map(&:name)).empty?
    end
    queries = dts.map do |dt|
      "DELETE FROM #{dt.table_name} WHERE import_id = #{id}"
    end
    queries.each { |q| Postgres::RemoteControl.query! q }
  end

  #
  # store data with nice filename and custom blob key

  # currently supported:
  #   store_data! :json, {some: "Hash"} => stored as json
  #   store_data! :json, '{"json": "string"}' => stored as json
  #   store_data! :csv, "csv,string" => stored as csv
  #   store_data! :txt, "some random text we parse later" => stored as plain text
  #
  def store_data!(format, data)
    raise "Import must be persisted to generate proper filename and blob key" unless persisted?

    extension = format

    data = data.to_json if data.is_a? Hash
    data = data.to_json if data.is_a? Array

    raise "Data Must be a string now, but is #{data.class}" unless data.is_a?(String)

    content_type = CONTENT_TYPES[extension]

    raise "Could not determine content type for #{extension}, import not saved to data lake" unless content_type

    fn = "#{id}-#{source_id}-#{source.kind}"
    # https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-keys.html#object-key-guidelines
    fn = fn.tr "^a-zA-Z0-9-_", "_"
    fn += ".#{extension}"

    # put each file into folders determined by a time format for better file management, default is by year-month-week/...
    key = "#{Time.zone.today.strftime(ENV.fetch('MINIO_PATH_STRFTIME_PREFIX', '%Y-%m-%W'))}/#{fn}"

    io = StringIO.new data

    file.attach io:, content_type:, filename: fn, key:, identify: false # identify: false disables automatic content-type detection of ActiveStorage
  end

  def self.run!(source, &block)
    i = Import.create!(source:)
    i.ingestion_started!
    block.call i
    i.ingestion_finished! unless i.failed?
    i
  end

  def owning_organization
    organization
  end
end

core/app/controllers/imports_controller.rb
# frozen_string_literal: true

class ImportsController < ApplicationController
  after_action :verify_authorized

  @header_section = "Import"

  def index
    @source_id = clean_source_id_param
    @source = Source.find_by id: @source_id

    @pagy, @imports = pagy(@source.imports.order(id: :desc))

    # for collection, check for privs on source as that's the important bit
    authorize @source, :view_data? # there is no source#index policy
  end

  def show
    @import = authorize Import.find params[:id]
    @page_title = t(".title", id: @import.id, source_name: @import.source.name)
  end

  def download
    @import = authorize Import.find params[:import_id]

    f, filename = if params[:recording]
                    [@import.recording, "source_#{@import.source_id}_#{@import.id}.webm"]
                  else
                    [@import.file, @import.file.filename.to_s]
                  end

    send_data f.download, filename:, content_type: f.content_type
  end

  def reprocess
    @import = authorize Import.find params[:import_id]
    @import.delete_data!
    @import.reprocess!

    redirect_to @import, notice: t(".reprocess")
  end

  def destroy
    @import = authorize Import.find params[:id]
    @import.destroy
    redirect_to source_path(@import.source), notice: t(".destroyed")
  end
end

core/app/views/imports/_progress.html.haml
- i = defined?(@import) ? @import : local_assigns[:import]
- raise "Either provide @import or local_assigns :import" unless i
-# - you have to spell tailwind classes, not just dynamically generate them otherwise they get minified and purged...
- border, bg = if i.failed? then %w[border-pink/50 bg-pink/50] elsif i.no_data? then %w[border-yellow/50 bg-yellow/50] else %w[border-primary/50 bg-primary/50] end

.w-60.bg-grey-1.border{class: border}
  .whitespace-nowrap.text-left.text-xs.font-medium.font-mono.px-1.py-1.leading-none{style: "width: #{i.state_percent}%", class: bg}
    = i.state.humanize

core/app/views/imports/_summary.html.haml
- i = defined?(@import) ? @import : local_assigns[:import]
- raise "Either provide @import or local_assigns :import" unless i
- state_color = if i.failed? then "text-pink" elsif i.processing_finished? then "text-primary" else "" end

.flex.justify-start.gap-x-3.text-center.items-center
  = render "imports/progress", import: i
  = i.time_s

core/app/views/imports/index.html.haml
= content_for :breadcrumbs do
  = render "breadcrumb" do
    = link_to "Import", projects_path
  = render "breadcrumb" do
    = link_to @source.project
  = render "breadcrumb" do
    = link_to @source

- if @source
  = content_for :page_title do
    Imports for Source #{@source}

  %table.table-auto.border-spacing-y-5.border-separate
    %tr
      %td.grid.grid-cols-1
        - @imports.each do |i|
          %span.text-sm.font-mono.mb-2
            = link_to i do
              = render "imports/summary", import: i
  = pagy_nav(@pagy).html_safe if @pagy.pages > 1

core/app/views/imports/show.html.haml
= content_for :breadcrumbs do
  = render "breadcrumb" do
    = link_to "Import", projects_path
  = render "breadcrumb" do
    = link_to @import.project
  = render "breadcrumb" do
    = link_to @import.source

= content_for :page_actions do
  .flex.flex-row
    - if policy(@import).reprocess?
      %span.ml-4.cursor-pointer.text-primary
        = link_to import_reprocess_path(@import), title: "Reprocess", data: {turbo_method: :post, turbo_confirm: t(:confirm_delete_and_reprocess)} do
          = heroicon "arrow-path"
    - if policy(@import).destroy?
      %span.ml-4.cursor-pointer.text-primary
        = link_to import_path(@import), id: :delete_source, title: "Delete", data: {turbo_method: :delete, turbo_confirm: t(:confirm_import_destroy)} do
          = heroicon "trash"

= render "tabs", titles: %w[Details Protocol] do
  = render "tab" do
    = render "attrib_table" do
      = render "attrib_tr", attr: "progress" do
        = render "progress"
      - if @import.error
        = render "attrib_tr", title: "Error" do
          .text-sm.font-mono
            = @import.error
      - if policy(@import).download?
        - if @import.file.attached?
          = render "attrib_tr", attr: "file" do
            %span{class: "text-primary hover:underline"}
              = link_to "Download", import_download_path(@import)
        - if @import.recording.attached?
          = render "attrib_tr", attr: "recording" do
            %span{class: "text-primary hover:underline"}
              = link_to "Download", import_download_path(@import, recording: true)
      = render "attrib_tr", attr: :last_imported_hint, model: @import

      = render "attrib_section", section: "Timing"
      - %w[created_at ingestion_started_at ingestion_finished_at processing_started_at processing_finished_at].each do |attr|
        = render "attrib_tr", attr: attr, model: @import

      = render "attrib_section", section: "Counts"
      -  %w[rows_duplicated rows_failed rows_inserted rows_updated].each do |attr|
        = render "attrib_tr", attr: attr, model: @import

  = render "tab" do
    %pre.text-sm.font-mono
      = @import.protocol